#!/bin/bash
yottadb -r GDE 
mupip CREATE -REGION=default
mupip set -region -journal=on,nobefore "*"
mupip SET -REGION -ACCESS_METHOD=MM "*"
# mupip SET -REGION -RES=2048 "*"
mupip SET -REGION -G=100000 "*"
# mupip SET -REGION -FLUSH_TIME=0:0:30 "*"
mupip EXTEND DEFAULT -BLOCKS=65535 
