#!/bin/bash
cd /$HOME/scripts
yottadb -r GDE @yottadb.gde
mupip CREATE
mupip set -ACCESS_METHOD=MM  -region "*"
mupip SET  -G=100000 -region "*"
mupip journal -recover -forward "*"
mupip set -journal=ENABLE,on,nobefore -region "*"
